package com.example.androidev;

public class QuestionAnswer {
    public static String question[] = {
            "What is an Activity in Android?",
            "What is the main UI component in Android?",
            "Which is the correct way to declare a Button in XML?",
            "What does `Intent` do in Android?",
            "Which of these is used for data storage in Android?",
            "What is the main function of a Service in Android?",
            "Which method is called to save data permanently in Android?",
            "Which Android component is used for networking?",
            "Which class is used for handling UI components in Android?",
            "How do you add a Fragment to an Activity?",
            "Which method is used to start an activity?",
            "What is the purpose of AndroidManifest.xml?",
            "How do you handle back press in Android?",
            "What is the Android SDK?",
            "How do you access shared preferences in Android?",
            "Which one is not a storage option in Android?",
            "How do you perform background tasks in Android?",
            "What is a ContentProvider in Android?",
            "What is RecyclerView used for?",
            "Which method starts an Activity with an Intent?",
            "Which is not a UI component in Android?",
            "Which one is used to schedule background tasks?",
            "What is a BroadcastReceiver?",
            "What is AsyncTask used for?",
            "How do you retrieve data from a database in Android?",
            "What is the purpose of ViewModel in Android?"
    };

    public static String choices[][] = {
            {"A UI element", "A background service", "A thread", "A database"},
            {"TextView", "Button", "ImageView", "RelativeLayout"},
            {"<Button>button</Button>", "<Button>Button</Button>", "<Button>button</Button>"},
            {"Send data between activities", "Start an activity", "Handle user input", "Load an image"},
            {"SharedPreferences", "SQLite", "Files", "Database"},
            {"Perform long-running operations", "Handle UI updates", "Update content in real time", "Receive broadcast messages"},
            {"SharedPreferences.put()", "SharedPreferences.get()", "SharedPreferences.edit()", "SharedPreferences.commit()"},
            {"HTTPClient", "Intent", "AsyncTask", "Runnable"},
            {"TextView", "Button", "LinearLayout", "Handler"},
            {"By FragmentManager", "By addFragment()", "By replaceFragment()", "By add() method"},
            {"startActivity()", "startService()", "sendIntent()", "start()"},
            {"Defines app components", "Defines layouts", "Defines activities", "Defines resources"},
            {"Override onBackPressed()", "Override onKeyDown()", "Override onBackClick()", "Override onBack()"},
            {"Software Development Kit", "System Development Kit", "Standard Data Kit", "Simple Development Kit"},
            {"SharedPreferences.get()", "SharedPreferences.put()", "SharedPreferences.edit()", "SharedPreferences.commit()"},
            {"SQLite", "Internal storage", "External storage", "Bitmap"},
            {"AsyncTask", "Thread", "Handler", "Loader"},
            {"To share data between apps", "To store data in the app", "To manage the UI", "To receive data from the network"},
            {"For displaying lists", "For handling user input", "For navigation", "For storing data"},
            {"startActivityForResult()", "startActivity()", "sendBroadcast()", "sendIntent()"},
            {"TextView", "ListView", "Button", "FrameLayout"},
            {"AlarmManager", "Thread", "Handler", "BroadcastReceiver"},
            {"Receives messages from other apps", "Handles background tasks", "Runs UI tasks", "Runs async tasks"},
            {"to fetch data", "to perform background work", "to update UI", "to send notifications"},
            {"SQLite", "SharedPreferences", "File System", "API"},
            {"To manage UI-related data"}
    };

    public static String correctAnswers[] = {
            "A UI element", "Button",
            "<Button>button</Button>",
            "Send data between activities",
            "SharedPreferences",
            "Perform long-running operations",
            "SharedPreferences.edit()",
            "HTTPClient", "TextView",
            "By FragmentManager",
            "startActivity()",
            "Defines app components",
            "Override onBackPressed()",
            "Software Development Kit",
            "SharedPreferences.get()",
            "SQLite", "AsyncTask",
            "To share data between apps",
            "For displaying lists",
            "startActivityForResult()",
            "TextView", "AlarmManager",
            "Receives messages from other apps",
            "to fetch data",
            "SQLite",
            "To manage UI-related data"
    };
}
